
function throwErrors(...args) {
  return args;
}

const errorName = 'ReferenceError';

export {
  throwErrors,
  errorName,
};
